language: bash
services: docker
env:
  global:
  - ARCH=amd64
  matrix:
  - PYTHON_VERSION=3.7.2
  - PYTHON_VERSION=3.6.8
  - PYTHON_VERSION=3.5.6
  - PYTHON_VERSION=3.4.9
  - DOCKER_IMAGE_TAG=$TRAVIS_BUILD_NUMBER DOCKER_BUILD_OPTIONS="-f Dockerfile-all"

script:
  - make build
  - make publish
after_script:
- docker images

